# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_language', models.CharField(max_length=100)),
                ('second_languages', models.CharField(blank=True, max_length=200, null=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_model.Syllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
